---
# tasks file for memoryleak.mysql
- name: Install yum repository package.
  package:
    name: "{{ mysql_package_url }}"
    state: present
  tags: ['package', 'mysql']

- name: Install server packages.
  package:
    name: "{{ item }}"
    state: present
  tags: ['package', 'mysql']
  with_items: "{{ mysql_server_packages }}"
  notify: mysqld-started-handler
  when: mysql_install_server

- name: Install client packages.
  package:
    name: "{{ item }}"
    state: present
  tags: ['package', 'mysql']
  with_items: "{{ mysql_client_packages }}"

- name: Check if .my.cnf exists.
  stat:
    path: "{{ansible_env.HOME}}/.my.cnf"
  register: register_my_cnf
  tags: ['stat', 'mysql']

- name: Start MySQL.
  meta: flush_handlers
  tags: ['meta', 'mysql']
  when: mysql_install_server

- name: Grep MySQL random password.
  command: "grep 'temporary password' /var/log/mysqld.log"
  register: register_mysql_password
  tags: ['command', 'mysql']
  when:
    - mysql_install_server
    - register_my_cnf.stat.exists == false

- name: Parse MySQL random password.
  set_fact:
    mysql_temporary_password: "{{ register_mysql_password.stdout | regex_search(': (.*)', '\\1')}}"
  tags: ['set_fact', 'mysql']
  when:
    - mysql_install_server
    - register_my_cnf.stat.exists == false

- name: Create .my.cnf file with random generated password.
  template:
    dest: "{{ansible_env.HOME}}/.my.cnf"
    mode: 0644
    src: my.cnf.j2
  tags: ['template', 'mysql']
  when:
    - mysql_install_server
    - register_my_cnf.stat.exists == false
